export const currencyConstants={
    GETALL_SUCCESS:'CURRENCY_GETALL_SUCCESS',
    GETALL_FAILURE:'CURRENCY_GETALL_FAILURE',
    GETALL_REQUEST:'CURRENCY_GETALL_REQUEST',

    GETBYID_SUCCESS:'CURRENCY_GETBYID_SUCESS',
    GETBYID_FAILURE:'CURRENCY_GETBYID_FAILURE',
    GETBYID_REQUEST:'CURRENCY_GETBYID_REQUEST',

    SEARCHQUERY_REQUEST:'CURRENCY_SEARCHQUERY_REQUEST',
    SEARCHQUERY_SUCCESS:'CURRENCY_SEARCHQUERY_SUCCESS',
    SEARCHQUERY_FAILURE:'CURRENCY_SEARCHQUERY_FAILURE',
    SEARCHQUERY_RESET:'CURRENCY_SEARCHQUERY_RESET'
};